### ISSUE TITLE
Any chance for a more relaxed license?

### ISSUE THREAD

**Issue by suddenelfilio** [Slion/SharpLibHid#4]
Did you intent to specify GPLv3 or was it more of a auto generated thing? Would you consider an MIT license or BSD 3 license?

**Comment by Slion** [comment]
GPLv3 is a conscious choice as it makes sure users contribute back to the project. If you want to use SharpLibHid under another license I would be happy to discuss licensing fees.

**Comment by suddenelfilio** [comment]
I don't see how forcing to disclose source code (as per GPLv3 is required) helps with contributing back, you can easily use the MIT or BSD 3 licenses for that. If it is a matter of wanting to earn money  you could make the library available using a Commercial License. I'll pass your invitation to discuss licensing fees on. Thanks!

**Comment by Slion** [comment]
I'm no licensing expert but I do believe that the only source code you are forced to disclose under GPLv3 is the one belonging to this library if ever you modify it. To me that's called contributing back. Hope you can make do with it. Otherwise please feel free to further explain why you can't use GPLv3.
